#ifndef ISR80H_H
#define ISR80H_H

enum SystemCommands {
    SYSTEM_COMMAND0_EXIT,
    SYSTEM_COMMAND1_PROMISE,
    SYSTEM_COMMAND2_DROP_PRIVILEGE,
    SYSTEM_COMMAND3_GET_KERNEL_INFO,
    SYSTEM_COMMAND4_PRINT,
    SYSTEM_COMMAND5_PUTCHAR,
    SYSTEM_COMMAND6_FB_CLEAR,
    SYSTEM_COMMAND7_GET_KEY,
    SYSTEM_COMMAND8_GET_KEY_EVENT,
    SYSTEM_COMMAND9_MALLOC,
    SYSTEM_COMMAND10_FREE,
    SYSTEM_COMMAND11_GET_PROCESS_ARGUMENT,
    SYSTEM_COMMAND12_SYSTEM,
    SYSTEM_COMMAND13_SYSTEM_AS,
    SYSTEM_COMMAND14_FORK,
    SYSTEM_COMMAND15_FORK_AS,
    SYSTEM_COMMAND16_GET_PROCESSES,
    SYSTEM_COMMAND17_TERMINATE_PROCESS,
    SYSTEM_COMMAND18_FOPEN,
    SYSTEM_COMMAND19_FCLOSE,
    SYSTEM_COMMAND20_FREAD,
    SYSTEM_COMMAND21_FSTAT,
    SYSTEM_COMMAND22_FSEEK,
    SYSTEM_COMMAND23_GET_TICKS_MS,
    SYSTEM_COMMAND24_DISABLE_CURSOR,
    SYSTEM_COMMAND25_ENABLE_CURSOR,
};

void isr80h_register_commands(); 

#endif