#ifndef ISR80H_H
#define ISR80H_H

enum SystemCommands {
    SYSTEM_COMMAND0_EXIT,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD_START,
    SYSTEM_COMMAND7_SYSTEM,
    SYSTEM_COMMAND8_GET_PROCESS_ARGUMENT,
    SYSTEM_COMMAND9_FB_CLEAR,
    SYSTEM_COMMAND10_PROMISE,
    SYSTEM_COMMAND11_SYSTEM_AS,
    SYSTEM_COMMAND12_FORK,
    SYSTEM_COMMAND13_FORK_AS,
    SYSTEM_COMMAND14_DROP_PRIVILEGE,
    SYSTEM_COMMAND15_GET_KERNEL_INFO,
    SYSTEM_COMMAND16_FOPEN,
    SYSTEM_COMMAND17_FCLOSE,
    SYSTEM_COMMAND18_FREAD,
    SYSTEM_COMMAND19_FSTAT,
    SYSTEM_COMMAND20_FSEEK,
};

void isr80h_register_commands(); 

#endif